Dev chen
YuTingLan/tourmind pull request #23
Opened 2023-04-21 12:19 UTC by chencac

首頁畫面
圖片部分設定像素功能我先註解掉，需要安裝Imagemagick。
需要上傳圖片功能的在需要的model掛上去就好。
記得params要加上:image跟images: []

2023-04-21 15:08 UTC, Hsubetty commented on config/routes.rb
小提醒:routes似乎顯示語法錯誤

2023-04-22 02:45 UTC, Hsubetty approved these changes

2023-04-22 02:45 UTC, Hsubetty commented on app/views/comments/_form.html.erb
> +          <%= form.radio_button :rating, i, class: "mr-1" %>
小建議:滿意度評分加入分數較直覺
有自己用"star_rating"的欄位加id去試.有印出分數,看這邊是否需要依照您原本欄位去調整,謝謝！

例-星級數:
<div class="mb-4">
    <%= form.label :星級數, class: "block mb-2 text-gray-700" %>
    <% (1..5).each do |i| %>
      <%= form.radio_button :star_rating, i, class: "mr-1", id: "star_rating#{i}" %>
      <%= form.label "star_rating#{i}", i, class: "mr-1 text-gray-700" %>
    <% end %>
  </div>

2023-04-22 16:16 UTC, YuTingLan approved these changes

2023-04-22 16:47 UTC, yangliang0514 approved these changes

2023-04-22 17:33 UTC, cacachang requested changes

2023-04-22 17:33 UTC, cacachang commented on test/models/comment_test.rb
> +require "test_helper"
沒有用到就可以刪掉喔

2023-04-22 17:33 UTC, cacachang commented on test/fixtures/comments.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
沒有要寫測試就可刪

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    def new
縮排

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
包在 before_action 中

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
同上

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
同上

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
同上

2023-04-22 17:33 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    if params[:keyword].present?
這是要做搜尋功能嗎？撈資料可以寫去 model 的 scope 中

2023-04-22 17:33 UTC, cacachang commented on db/migrate/20230419040700_create_comments.rb
> +      t.string :location
這邊的 location 指的是蝦米？

2023-04-22 17:33 UTC, cacachang commented on db/migrate/20230419052640_add_image_to_restaurants.rb
> +    add_column :comments, :image, :string
為什麼這邊是使用 string ，下面是使用 json
* PostgreSQL 有支援 json

<img width="805" alt="image" src="https://user-images.githubusercontent.com/85012510/233797382-d5a424d1-4d78-424d-9fd2-8798bc27f484.png">

2023-04-22 17:33 UTC, cacachang commented on app/javascript/controllers/moving_controller.js
> +    console.log('updateSlides has been executed')
刪掉

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/index.html.erb
> +    <div class="flex-shrink-0 w-full  p-4 ">
縮排

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/index.html.erb
> +        <%= link_to comment.author, comment_path(comment.id) %>
如果 author 是 nil 的話，就會變成這樣

<img width="188" alt="image" src="https://user-images.githubusercontent.com/85012510/233797993-e8fa040b-db7f-4533-ab3a-fb85b903cca4.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/85012510/233798010-fcf5e28f-b4ce-4ed2-b0fb-7daa5711960c.png">

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/index.html.erb
> +          <%= link_to '編輯', edit_comment_path(comment.id) %>
可以簡寫成這樣 
`<%= link_to '編輯', edit_comment_path(comment) %>`

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/index.html.erb
> +          <%= link_to '刪除', comment_path(comment.id), method: "delete", data: { confirm: 'Are you sure?' } %>
同上

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/new.html.erb
> +<%= render "form", comments: @aurnt %>
@aurnt 是什麼呢？

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/show.html.erb
> +      <%= image_tag @comment.image.url, class: 'mt-2 max-w-full h-auto' if @comment.image.url.present? %>
這是未來的功能嗎？想說圖片是用上傳的，而且 model 的 image 欄位也沒有 url

2023-04-22 17:33 UTC, cacachang commented on app/views/comments/edit.html.erb
> +<%= render "form", comments: @aurnt %>
@aurnt 是什麼呢？

2023-04-22 17:33 UTC, cacachang commented on app/models/comment.rb
> +  # 這是掛載在Comment會需要圖片上傳功能去model掛上去就好
可以加個欄位驗證

2023-04-22 18:10 UTC, chencac commented on db/migrate/20230419052640_add_image_to_restaurants.rb
> +    add_column :comments, :image, :string
<img width="440" alt="截圖 2023-04-23 上午2 08 18" src="https://user-images.githubusercontent.com/126404868/233799995-f5cc6b17-02f0-4bc1-9046-d9aa74102cf9.png">
<img width="336" alt="截圖 2023-04-23 上午2 08 24" src="https://user-images.githubusercontent.com/126404868/233799997-af14c1b6-a07e-4661-928b-314f9bdd55bd.png">
多檔上傳使用json，但是為什麼單獨檔案上傳要使用json

2023-04-22 21:35 UTC, CCTWeng approved these changes

2023-04-24 03:26 UTC, closed without merging